plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme  

kramdown:
  parse_block_html: false

exclude: ['vendor', 'setup.sh', 'jekyll.sh']
include:
  - _pages

timezone: America/Los_Angeles

title: "UCSB CCS Computing"
github_url: https://github.com/ucsb-ccs-computing/ucsb-ccs-computing.github.io


timezone: America/Los_Angeles

collections:

  faculty:
    output: true
    permalink: /faculty/:path/

  students:
    output: true
    permalink: /students/:path/

  alumni:
    output: true
    permalink: /alumni/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

  - scope:
      path: ""
      type: students
    values:
      layout: person

  - scope:
      path: ""
      type: alumni
    values:
      layout: person

  - scope:
      path: ""
      type: faculty
    values:
      layout: person


